# Generated by Django 4.2.3 on 2024-02-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_menuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="inventory",
            field=models.IntegerField(default=1),
        ),
    ]
